[package]
name = "queen-sweep-benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
queen-sweep-core = { path = "../queen-sweep-core", features = ["display"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
